#region Copyright
/*
Copyright 2014 Cluster Reply s.r.l.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
#endregion
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Oasis.Ubl.v21</NameSpace><Collection>ObservableCollection</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Oasis.Ubl.v21 {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.ObjectModel;
    
    
    public partial class TransportationStatusRequestType : System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<UBLExtensionType> uBLExtensionsField;
        
        private UBLVersionIDType uBLVersionIDField;
        
        private CustomizationIDType customizationIDField;
        
        private ProfileIDType profileIDField;
        
        private ProfileExecutionIDType profileExecutionIDField;
        
        private IDType idField;
        
        private CarrierAssignedIDType carrierAssignedIDField;
        
        private UUIDType uUIDField;
        
        private IssueDateType issueDateField;
        
        private IssueTimeType issueTimeField;
        
        private NameType1 nameField;
        
        private ObservableCollection<DescriptionType> descriptionField;
        
        private ObservableCollection<NoteType> noteField;
        
        private ShippingOrderIDType shippingOrderIDField;
        
        private OtherInstructionType otherInstructionField;
        
        private TransportationStatusTypeCodeType transportationStatusTypeCodeField;
        
        private PartyType senderPartyField;
        
        private PartyType receiverPartyField;
        
        private DocumentReferenceType transportExecutionPlanDocumentReferenceField;
        
        private ObservableCollection<ConsignmentType> consignmentField;
        
        private ObservableCollection<DocumentReferenceType> documentReferenceField;
        
        private ObservableCollection<SignatureType> signatureField;
        
        private ObservableCollection<LocationType1> requestedStatusLocationField;
        
        private ObservableCollection<PeriodType> requestedStatusPeriodField;
        
        private static System.Xml.Serialization.XmlSerializer serializer;
        
        public TransportationStatusRequestType() {
            this.requestedStatusPeriodField = new ObservableCollection<PeriodType>();
            this.requestedStatusLocationField = new ObservableCollection<LocationType1>();
            this.signatureField = new ObservableCollection<SignatureType>();
            this.documentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.consignmentField = new ObservableCollection<ConsignmentType>();
            this.transportExecutionPlanDocumentReferenceField = new DocumentReferenceType();
            this.receiverPartyField = new PartyType();
            this.senderPartyField = new PartyType();
            this.transportationStatusTypeCodeField = new TransportationStatusTypeCodeType();
            this.otherInstructionField = new OtherInstructionType();
            this.shippingOrderIDField = new ShippingOrderIDType();
            this.noteField = new ObservableCollection<NoteType>();
            this.descriptionField = new ObservableCollection<DescriptionType>();
            this.nameField = new NameType1();
            this.issueTimeField = new IssueTimeType();
            this.issueDateField = new IssueDateType();
            this.uUIDField = new UUIDType();
            this.carrierAssignedIDField = new CarrierAssignedIDType();
            this.idField = new IDType();
            this.profileExecutionIDField = new ProfileExecutionIDType();
            this.profileIDField = new ProfileIDType();
            this.customizationIDField = new CustomizationIDType();
            this.uBLVersionIDField = new UBLVersionIDType();
            this.uBLExtensionsField = new ObservableCollection<UBLExtensionType>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLExtension", IsNullable=false)]
        public ObservableCollection<UBLExtensionType> UBLExtensions {
            get {
                return this.uBLExtensionsField;
            }
            set {
                if ((this.uBLExtensionsField != null)) {
                    if ((uBLExtensionsField.Equals(value) != true)) {
                        this.uBLExtensionsField = value;
                        this.OnPropertyChanged("UBLExtensions");
                    }
                }
                else {
                    this.uBLExtensionsField = value;
                    this.OnPropertyChanged("UBLExtensions");
                }
            }
        }
        
        public UBLVersionIDType UBLVersionID {
            get {
                return this.uBLVersionIDField;
            }
            set {
                if ((this.uBLVersionIDField != null)) {
                    if ((uBLVersionIDField.Equals(value) != true)) {
                        this.uBLVersionIDField = value;
                        this.OnPropertyChanged("UBLVersionID");
                    }
                }
                else {
                    this.uBLVersionIDField = value;
                    this.OnPropertyChanged("UBLVersionID");
                }
            }
        }
        
        public CustomizationIDType CustomizationID {
            get {
                return this.customizationIDField;
            }
            set {
                if ((this.customizationIDField != null)) {
                    if ((customizationIDField.Equals(value) != true)) {
                        this.customizationIDField = value;
                        this.OnPropertyChanged("CustomizationID");
                    }
                }
                else {
                    this.customizationIDField = value;
                    this.OnPropertyChanged("CustomizationID");
                }
            }
        }
        
        public ProfileIDType ProfileID {
            get {
                return this.profileIDField;
            }
            set {
                if ((this.profileIDField != null)) {
                    if ((profileIDField.Equals(value) != true)) {
                        this.profileIDField = value;
                        this.OnPropertyChanged("ProfileID");
                    }
                }
                else {
                    this.profileIDField = value;
                    this.OnPropertyChanged("ProfileID");
                }
            }
        }
        
        public ProfileExecutionIDType ProfileExecutionID {
            get {
                return this.profileExecutionIDField;
            }
            set {
                if ((this.profileExecutionIDField != null)) {
                    if ((profileExecutionIDField.Equals(value) != true)) {
                        this.profileExecutionIDField = value;
                        this.OnPropertyChanged("ProfileExecutionID");
                    }
                }
                else {
                    this.profileExecutionIDField = value;
                    this.OnPropertyChanged("ProfileExecutionID");
                }
            }
        }
        
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                if ((this.idField != null)) {
                    if ((idField.Equals(value) != true)) {
                        this.idField = value;
                        this.OnPropertyChanged("ID");
                    }
                }
                else {
                    this.idField = value;
                    this.OnPropertyChanged("ID");
                }
            }
        }
        
        public CarrierAssignedIDType CarrierAssignedID {
            get {
                return this.carrierAssignedIDField;
            }
            set {
                if ((this.carrierAssignedIDField != null)) {
                    if ((carrierAssignedIDField.Equals(value) != true)) {
                        this.carrierAssignedIDField = value;
                        this.OnPropertyChanged("CarrierAssignedID");
                    }
                }
                else {
                    this.carrierAssignedIDField = value;
                    this.OnPropertyChanged("CarrierAssignedID");
                }
            }
        }
        
        public UUIDType UUID {
            get {
                return this.uUIDField;
            }
            set {
                if ((this.uUIDField != null)) {
                    if ((uUIDField.Equals(value) != true)) {
                        this.uUIDField = value;
                        this.OnPropertyChanged("UUID");
                    }
                }
                else {
                    this.uUIDField = value;
                    this.OnPropertyChanged("UUID");
                }
            }
        }
        
        public IssueDateType IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                if ((this.issueDateField != null)) {
                    if ((issueDateField.Equals(value) != true)) {
                        this.issueDateField = value;
                        this.OnPropertyChanged("IssueDate");
                    }
                }
                else {
                    this.issueDateField = value;
                    this.OnPropertyChanged("IssueDate");
                }
            }
        }
        
        public IssueTimeType IssueTime {
            get {
                return this.issueTimeField;
            }
            set {
                if ((this.issueTimeField != null)) {
                    if ((issueTimeField.Equals(value) != true)) {
                        this.issueTimeField = value;
                        this.OnPropertyChanged("IssueTime");
                    }
                }
                else {
                    this.issueTimeField = value;
                    this.OnPropertyChanged("IssueTime");
                }
            }
        }
        
        public NameType1 Name {
            get {
                return this.nameField;
            }
            set {
                if ((this.nameField != null)) {
                    if ((nameField.Equals(value) != true)) {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }
        
        public ObservableCollection<DescriptionType> Description {
            get {
                return this.descriptionField;
            }
            set {
                if ((this.descriptionField != null)) {
                    if ((descriptionField.Equals(value) != true)) {
                        this.descriptionField = value;
                        this.OnPropertyChanged("Description");
                    }
                }
                else {
                    this.descriptionField = value;
                    this.OnPropertyChanged("Description");
                }
            }
        }
        
        public ObservableCollection<NoteType> Note {
            get {
                return this.noteField;
            }
            set {
                if ((this.noteField != null)) {
                    if ((noteField.Equals(value) != true)) {
                        this.noteField = value;
                        this.OnPropertyChanged("Note");
                    }
                }
                else {
                    this.noteField = value;
                    this.OnPropertyChanged("Note");
                }
            }
        }
        
        public ShippingOrderIDType ShippingOrderID {
            get {
                return this.shippingOrderIDField;
            }
            set {
                if ((this.shippingOrderIDField != null)) {
                    if ((shippingOrderIDField.Equals(value) != true)) {
                        this.shippingOrderIDField = value;
                        this.OnPropertyChanged("ShippingOrderID");
                    }
                }
                else {
                    this.shippingOrderIDField = value;
                    this.OnPropertyChanged("ShippingOrderID");
                }
            }
        }
        
        public OtherInstructionType OtherInstruction {
            get {
                return this.otherInstructionField;
            }
            set {
                if ((this.otherInstructionField != null)) {
                    if ((otherInstructionField.Equals(value) != true)) {
                        this.otherInstructionField = value;
                        this.OnPropertyChanged("OtherInstruction");
                    }
                }
                else {
                    this.otherInstructionField = value;
                    this.OnPropertyChanged("OtherInstruction");
                }
            }
        }
        
        public TransportationStatusTypeCodeType TransportationStatusTypeCode {
            get {
                return this.transportationStatusTypeCodeField;
            }
            set {
                if ((this.transportationStatusTypeCodeField != null)) {
                    if ((transportationStatusTypeCodeField.Equals(value) != true)) {
                        this.transportationStatusTypeCodeField = value;
                        this.OnPropertyChanged("TransportationStatusTypeCode");
                    }
                }
                else {
                    this.transportationStatusTypeCodeField = value;
                    this.OnPropertyChanged("TransportationStatusTypeCode");
                }
            }
        }
        
        public PartyType SenderParty {
            get {
                return this.senderPartyField;
            }
            set {
                if ((this.senderPartyField != null)) {
                    if ((senderPartyField.Equals(value) != true)) {
                        this.senderPartyField = value;
                        this.OnPropertyChanged("SenderParty");
                    }
                }
                else {
                    this.senderPartyField = value;
                    this.OnPropertyChanged("SenderParty");
                }
            }
        }
        
        public PartyType ReceiverParty {
            get {
                return this.receiverPartyField;
            }
            set {
                if ((this.receiverPartyField != null)) {
                    if ((receiverPartyField.Equals(value) != true)) {
                        this.receiverPartyField = value;
                        this.OnPropertyChanged("ReceiverParty");
                    }
                }
                else {
                    this.receiverPartyField = value;
                    this.OnPropertyChanged("ReceiverParty");
                }
            }
        }
        
        public DocumentReferenceType TransportExecutionPlanDocumentReference {
            get {
                return this.transportExecutionPlanDocumentReferenceField;
            }
            set {
                if ((this.transportExecutionPlanDocumentReferenceField != null)) {
                    if ((transportExecutionPlanDocumentReferenceField.Equals(value) != true)) {
                        this.transportExecutionPlanDocumentReferenceField = value;
                        this.OnPropertyChanged("TransportExecutionPlanDocumentReference");
                    }
                }
                else {
                    this.transportExecutionPlanDocumentReferenceField = value;
                    this.OnPropertyChanged("TransportExecutionPlanDocumentReference");
                }
            }
        }
        
        public ObservableCollection<ConsignmentType> Consignment {
            get {
                return this.consignmentField;
            }
            set {
                if ((this.consignmentField != null)) {
                    if ((consignmentField.Equals(value) != true)) {
                        this.consignmentField = value;
                        this.OnPropertyChanged("Consignment");
                    }
                }
                else {
                    this.consignmentField = value;
                    this.OnPropertyChanged("Consignment");
                }
            }
        }
        
        public ObservableCollection<DocumentReferenceType> DocumentReference {
            get {
                return this.documentReferenceField;
            }
            set {
                if ((this.documentReferenceField != null)) {
                    if ((documentReferenceField.Equals(value) != true)) {
                        this.documentReferenceField = value;
                        this.OnPropertyChanged("DocumentReference");
                    }
                }
                else {
                    this.documentReferenceField = value;
                    this.OnPropertyChanged("DocumentReference");
                }
            }
        }
        
        public ObservableCollection<SignatureType> Signature {
            get {
                return this.signatureField;
            }
            set {
                if ((this.signatureField != null)) {
                    if ((signatureField.Equals(value) != true)) {
                        this.signatureField = value;
                        this.OnPropertyChanged("Signature");
                    }
                }
                else {
                    this.signatureField = value;
                    this.OnPropertyChanged("Signature");
                }
            }
        }
        
        public ObservableCollection<LocationType1> RequestedStatusLocation {
            get {
                return this.requestedStatusLocationField;
            }
            set {
                if ((this.requestedStatusLocationField != null)) {
                    if ((requestedStatusLocationField.Equals(value) != true)) {
                        this.requestedStatusLocationField = value;
                        this.OnPropertyChanged("RequestedStatusLocation");
                    }
                }
                else {
                    this.requestedStatusLocationField = value;
                    this.OnPropertyChanged("RequestedStatusLocation");
                }
            }
        }
        
        public ObservableCollection<PeriodType> RequestedStatusPeriod {
            get {
                return this.requestedStatusPeriodField;
            }
            set {
                if ((this.requestedStatusPeriodField != null)) {
                    if ((requestedStatusPeriodField.Equals(value) != true)) {
                        this.requestedStatusPeriodField = value;
                        this.OnPropertyChanged("RequestedStatusPeriod");
                    }
                }
                else {
                    this.requestedStatusPeriodField = value;
                    this.OnPropertyChanged("RequestedStatusPeriod");
                }
            }
        }
        
        private static System.Xml.Serialization.XmlSerializer Serializer {
            get {
                if ((serializer == null)) {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(TransportationStatusRequestType));
                }
                return serializer;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current TransportationStatusRequestType object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize() {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally {
                if ((streamReader != null)) {
                    streamReader.Dispose();
                }
                if ((memoryStream != null)) {
                    memoryStream.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes workflow markup into an TransportationStatusRequestType object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output TransportationStatusRequestType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out TransportationStatusRequestType obj, out System.Exception exception) {
            exception = null;
            obj = default(TransportationStatusRequestType);
            try {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool Deserialize(string xml, out TransportationStatusRequestType obj) {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }
        
        public static TransportationStatusRequestType Deserialize(string xml) {
            System.IO.StringReader stringReader = null;
            try {
                stringReader = new System.IO.StringReader(xml);
                return ((TransportationStatusRequestType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally {
                if ((stringReader != null)) {
                    stringReader.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Serializes current TransportationStatusRequestType object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception) {
            exception = null;
            try {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e) {
                exception = e;
                return false;
            }
        }
        
        public virtual void SaveToFile(string fileName) {
            System.IO.StreamWriter streamWriter = null;
            try {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally {
                if ((streamWriter != null)) {
                    streamWriter.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes xml markup from file into an TransportationStatusRequestType object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output TransportationStatusRequestType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out TransportationStatusRequestType obj, out System.Exception exception) {
            exception = null;
            obj = default(TransportationStatusRequestType);
            try {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool LoadFromFile(string fileName, out TransportationStatusRequestType obj) {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }
        
        public static TransportationStatusRequestType LoadFromFile(string fileName) {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally {
                if ((file != null)) {
                    file.Dispose();
                }
                if ((sr != null)) {
                    sr.Dispose();
                }
            }
        }
        #endregion
        
        #region Clone method
        /// <summary>
        /// Create a clone of this TransportationStatusRequestType object
        /// </summary>
        public virtual TransportationStatusRequestType Clone() {
            return ((TransportationStatusRequestType)(this.MemberwiseClone()));
        }
        #endregion
    }
}
