#region Copyright
/*
Copyright 2014 Cluster Reply s.r.l.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
#endregion
// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Oasis.Ubl.v21</NameSpace><Collection>ObservableCollection</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Oasis.Ubl.v21 {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.ObjectModel;


     [System.Xml.Serialization.XmlRootAttribute("Invoice", Namespace = "urn:oasis:names:specification:ubl:schema:xsd:Invoice-2", IsNullable = false)]

    public partial class InvoiceType : System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<UBLExtensionType> uBLExtensionsField;
        
        private UBLVersionIDType uBLVersionIDField;
        
        private CustomizationIDType customizationIDField;
        
        private ProfileIDType profileIDField;
        
        private ProfileExecutionIDType profileExecutionIDField;
        
        private IDType idField;
        
        private CopyIndicatorType copyIndicatorField;
        
        private UUIDType uUIDField;
        
        private IssueDateType issueDateField;
        
        private IssueTimeType issueTimeField;
        
        private DueDateType dueDateField;
        
        private InvoiceTypeCodeType invoiceTypeCodeField;
        
        private ObservableCollection<NoteType> noteField;
        
        private TaxPointDateType taxPointDateField;
        
        private DocumentCurrencyCodeType documentCurrencyCodeField;
        
        private TaxCurrencyCodeType taxCurrencyCodeField;
        
        private PricingCurrencyCodeType pricingCurrencyCodeField;
        
        private PaymentCurrencyCodeType paymentCurrencyCodeField;
        
        private PaymentAlternativeCurrencyCodeType paymentAlternativeCurrencyCodeField;
        
        private AccountingCostCodeType accountingCostCodeField;
        
        private AccountingCostType accountingCostField;
        
        private LineCountNumericType lineCountNumericField;
        
        private BuyerReferenceType buyerReferenceField;
        
        private ObservableCollection<PeriodType> invoicePeriodField;
        
        private OrderReferenceType orderReferenceField;
        
        private ObservableCollection<BillingReferenceType> billingReferenceField;
        
        private ObservableCollection<DocumentReferenceType> despatchDocumentReferenceField;
        
        private ObservableCollection<DocumentReferenceType> receiptDocumentReferenceField;
        
        private ObservableCollection<DocumentReferenceType> statementDocumentReferenceField;
        
        private ObservableCollection<DocumentReferenceType> originatorDocumentReferenceField;
        
        private ObservableCollection<DocumentReferenceType> contractDocumentReferenceField;
        
        private ObservableCollection<DocumentReferenceType> additionalDocumentReferenceField;
        
        private ObservableCollection<ProjectReferenceType> projectReferenceField;
        
        private ObservableCollection<SignatureType> signatureField;
        
        private SupplierPartyType accountingSupplierPartyField;
        
        private CustomerPartyType accountingCustomerPartyField;
        
        private PartyType payeePartyField;
        
        private CustomerPartyType buyerCustomerPartyField;
        
        private SupplierPartyType sellerSupplierPartyField;
        
        private PartyType taxRepresentativePartyField;
        
        private ObservableCollection<DeliveryType> deliveryField;
        
        private DeliveryTermsType deliveryTermsField;
        
        private ObservableCollection<PaymentMeansType> paymentMeansField;
        
        private ObservableCollection<PaymentTermsType> paymentTermsField;
        
        private ObservableCollection<PaymentType> prepaidPaymentField;
        
        private ObservableCollection<AllowanceChargeType> allowanceChargeField;
        
        private ExchangeRateType taxExchangeRateField;
        
        private ExchangeRateType pricingExchangeRateField;
        
        private ExchangeRateType paymentExchangeRateField;
        
        private ExchangeRateType paymentAlternativeExchangeRateField;
        
        private ObservableCollection<TaxTotalType> taxTotalField;
        
        private ObservableCollection<TaxTotalType> withholdingTaxTotalField;
        
        private MonetaryTotalType legalMonetaryTotalField;
        
        private ObservableCollection<InvoiceLineType> invoiceLineField;
        
        private static System.Xml.Serialization.XmlSerializer serializer;
        
        public InvoiceType() {
            this.invoiceLineField = new ObservableCollection<InvoiceLineType>();
            this.legalMonetaryTotalField = new MonetaryTotalType();
            this.withholdingTaxTotalField = new ObservableCollection<TaxTotalType>();
            this.taxTotalField = new ObservableCollection<TaxTotalType>();
            this.paymentAlternativeExchangeRateField = new ExchangeRateType();
            this.paymentExchangeRateField = new ExchangeRateType();
            this.pricingExchangeRateField = new ExchangeRateType();
            this.taxExchangeRateField = new ExchangeRateType();
            this.allowanceChargeField = new ObservableCollection<AllowanceChargeType>();
            this.prepaidPaymentField = new ObservableCollection<PaymentType>();
            this.paymentTermsField = new ObservableCollection<PaymentTermsType>();
            this.paymentMeansField = new ObservableCollection<PaymentMeansType>();
            this.deliveryTermsField = new DeliveryTermsType();
            this.deliveryField = new ObservableCollection<DeliveryType>();
            this.taxRepresentativePartyField = new PartyType();
            this.sellerSupplierPartyField = new SupplierPartyType();
            this.buyerCustomerPartyField = new CustomerPartyType();
            this.payeePartyField = new PartyType();
            this.accountingCustomerPartyField = new CustomerPartyType();
            this.accountingSupplierPartyField = new SupplierPartyType();
            this.signatureField = new ObservableCollection<SignatureType>();
            this.projectReferenceField = new ObservableCollection<ProjectReferenceType>();
            this.additionalDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.contractDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.originatorDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.statementDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.receiptDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.despatchDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.billingReferenceField = new ObservableCollection<BillingReferenceType>();
            this.orderReferenceField = new OrderReferenceType();
            this.invoicePeriodField = new ObservableCollection<PeriodType>();
            this.buyerReferenceField = new BuyerReferenceType();
            this.lineCountNumericField = new LineCountNumericType();
            this.accountingCostField = new AccountingCostType();
            this.accountingCostCodeField = new AccountingCostCodeType();
            this.paymentAlternativeCurrencyCodeField = new PaymentAlternativeCurrencyCodeType();
            this.paymentCurrencyCodeField = new PaymentCurrencyCodeType();
            this.pricingCurrencyCodeField = new PricingCurrencyCodeType();
            this.taxCurrencyCodeField = new TaxCurrencyCodeType();
            this.documentCurrencyCodeField = new DocumentCurrencyCodeType();
            this.taxPointDateField = new TaxPointDateType();
            this.noteField = new ObservableCollection<NoteType>();
            this.invoiceTypeCodeField = new InvoiceTypeCodeType();
            this.dueDateField = new DueDateType();
            this.issueTimeField = new IssueTimeType();
            this.issueDateField = new IssueDateType();
            this.uUIDField = new UUIDType();
            this.copyIndicatorField = new CopyIndicatorType();
            this.idField = new IDType();
            this.profileExecutionIDField = new ProfileExecutionIDType();
            this.profileIDField = new ProfileIDType();
            this.customizationIDField = new CustomizationIDType();
            this.uBLVersionIDField = new UBLVersionIDType();
            this.uBLExtensionsField = new ObservableCollection<UBLExtensionType>();
        }

        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLExtension", IsNullable = false)]
        public ObservableCollection<UBLExtensionType> UBLExtensions {
            get {
                return this.uBLExtensionsField;
            }
            set {
                if ((this.uBLExtensionsField != null)) {
                    if ((uBLExtensionsField.Equals(value) != true)) {
                        this.uBLExtensionsField = value;
                        this.OnPropertyChanged("UBLExtensions");
                    }
                }
                else {
                    this.uBLExtensionsField = value;
                    this.OnPropertyChanged("UBLExtensions");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public UBLVersionIDType UBLVersionID {
            get {
                return this.uBLVersionIDField;
            }
            set {
                if ((this.uBLVersionIDField != null)) {
                    if ((uBLVersionIDField.Equals(value) != true)) {
                        this.uBLVersionIDField = value;
                        this.OnPropertyChanged("UBLVersionID");
                    }
                }
                else {
                    this.uBLVersionIDField = value;
                    this.OnPropertyChanged("UBLVersionID");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public CustomizationIDType CustomizationID {
            get {
                return this.customizationIDField;
            }
            set {
                if ((this.customizationIDField != null)) {
                    if ((customizationIDField.Equals(value) != true)) {
                        this.customizationIDField = value;
                        this.OnPropertyChanged("CustomizationID");
                    }
                }
                else {
                    this.customizationIDField = value;
                    this.OnPropertyChanged("CustomizationID");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public ProfileIDType ProfileID {
            get {
                return this.profileIDField;
            }
            set {
                if ((this.profileIDField != null)) {
                    if ((profileIDField.Equals(value) != true)) {
                        this.profileIDField = value;
                        this.OnPropertyChanged("ProfileID");
                    }
                }
                else {
                    this.profileIDField = value;
                    this.OnPropertyChanged("ProfileID");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public ProfileExecutionIDType ProfileExecutionID {
            get {
                return this.profileExecutionIDField;
            }
            set {
                if ((this.profileExecutionIDField != null)) {
                    if ((profileExecutionIDField.Equals(value) != true)) {
                        this.profileExecutionIDField = value;
                        this.OnPropertyChanged("ProfileExecutionID");
                    }
                }
                else {
                    this.profileExecutionIDField = value;
                    this.OnPropertyChanged("ProfileExecutionID");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                if ((this.idField != null)) {
                    if ((idField.Equals(value) != true)) {
                        this.idField = value;
                        this.OnPropertyChanged("ID");
                    }
                }
                else {
                    this.idField = value;
                    this.OnPropertyChanged("ID");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public CopyIndicatorType CopyIndicator {
            get {
                return this.copyIndicatorField;
            }
            set {
                if ((this.copyIndicatorField != null)) {
                    if ((copyIndicatorField.Equals(value) != true)) {
                        this.copyIndicatorField = value;
                        this.OnPropertyChanged("CopyIndicator");
                    }
                }
                else {
                    this.copyIndicatorField = value;
                    this.OnPropertyChanged("CopyIndicator");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public UUIDType UUID {
            get {
                return this.uUIDField;
            }
            set {
                if ((this.uUIDField != null)) {
                    if ((uUIDField.Equals(value) != true)) {
                        this.uUIDField = value;
                        this.OnPropertyChanged("UUID");
                    }
                }
                else {
                    this.uUIDField = value;
                    this.OnPropertyChanged("UUID");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IssueDateType IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                if ((this.issueDateField != null)) {
                    if ((issueDateField.Equals(value) != true)) {
                        this.issueDateField = value;
                        this.OnPropertyChanged("IssueDate");
                    }
                }
                else {
                    this.issueDateField = value;
                    this.OnPropertyChanged("IssueDate");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public IssueTimeType IssueTime {
            get {
                return this.issueTimeField;
            }
            set {
                if ((this.issueTimeField != null)) {
                    if ((issueTimeField.Equals(value) != true)) {
                        this.issueTimeField = value;
                        this.OnPropertyChanged("IssueTime");
                    }
                }
                else {
                    this.issueTimeField = value;
                    this.OnPropertyChanged("IssueTime");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public DueDateType DueDate {
            get {
                return this.dueDateField;
            }
            set {
                if ((this.dueDateField != null)) {
                    if ((dueDateField.Equals(value) != true)) {
                        this.dueDateField = value;
                        this.OnPropertyChanged("DueDate");
                    }
                }
                else {
                    this.dueDateField = value;
                    this.OnPropertyChanged("DueDate");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public InvoiceTypeCodeType InvoiceTypeCode {
            get {
                return this.invoiceTypeCodeField;
            }
            set {
                if ((this.invoiceTypeCodeField != null)) {
                    if ((invoiceTypeCodeField.Equals(value) != true)) {
                        this.invoiceTypeCodeField = value;
                        this.OnPropertyChanged("InvoiceTypeCode");
                    }
                }
                else {
                    this.invoiceTypeCodeField = value;
                    this.OnPropertyChanged("InvoiceTypeCode");
                }
            }
        }


        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public ObservableCollection<NoteType> Note {
            get {
                return this.noteField;
            }
            set {
                if ((this.noteField != null)) {
                    if ((noteField.Equals(value) != true)) {
                        this.noteField = value;
                        this.OnPropertyChanged("Note");
                    }
                }
                else {
                    this.noteField = value;
                    this.OnPropertyChanged("Note");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TaxPointDateType TaxPointDate {
            get {
                return this.taxPointDateField;
            }
            set {
                if ((this.taxPointDateField != null)) {
                    if ((taxPointDateField.Equals(value) != true)) {
                        this.taxPointDateField = value;
                        this.OnPropertyChanged("TaxPointDate");
                    }
                }
                else {
                    this.taxPointDateField = value;
                    this.OnPropertyChanged("TaxPointDate");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public DocumentCurrencyCodeType DocumentCurrencyCode {
            get {
                return this.documentCurrencyCodeField;
            }
            set {
                if ((this.documentCurrencyCodeField != null)) {
                    if ((documentCurrencyCodeField.Equals(value) != true)) {
                        this.documentCurrencyCodeField = value;
                        this.OnPropertyChanged("DocumentCurrencyCode");
                    }
                }
                else {
                    this.documentCurrencyCodeField = value;
                    this.OnPropertyChanged("DocumentCurrencyCode");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public TaxCurrencyCodeType TaxCurrencyCode {
            get {
                return this.taxCurrencyCodeField;
            }
            set {
                if ((this.taxCurrencyCodeField != null)) {
                    if ((taxCurrencyCodeField.Equals(value) != true)) {
                        this.taxCurrencyCodeField = value;
                        this.OnPropertyChanged("TaxCurrencyCode");
                    }
                }
                else {
                    this.taxCurrencyCodeField = value;
                    this.OnPropertyChanged("TaxCurrencyCode");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public PricingCurrencyCodeType PricingCurrencyCode {
            get {
                return this.pricingCurrencyCodeField;
            }
            set {
                if ((this.pricingCurrencyCodeField != null)) {
                    if ((pricingCurrencyCodeField.Equals(value) != true)) {
                        this.pricingCurrencyCodeField = value;
                        this.OnPropertyChanged("PricingCurrencyCode");
                    }
                }
                else {
                    this.pricingCurrencyCodeField = value;
                    this.OnPropertyChanged("PricingCurrencyCode");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public PaymentCurrencyCodeType PaymentCurrencyCode {
            get {
                return this.paymentCurrencyCodeField;
            }
            set {
                if ((this.paymentCurrencyCodeField != null)) {
                    if ((paymentCurrencyCodeField.Equals(value) != true)) {
                        this.paymentCurrencyCodeField = value;
                        this.OnPropertyChanged("PaymentCurrencyCode");
                    }
                }
                else {
                    this.paymentCurrencyCodeField = value;
                    this.OnPropertyChanged("PaymentCurrencyCode");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public PaymentAlternativeCurrencyCodeType PaymentAlternativeCurrencyCode {
            get {
                return this.paymentAlternativeCurrencyCodeField;
            }
            set {
                if ((this.paymentAlternativeCurrencyCodeField != null)) {
                    if ((paymentAlternativeCurrencyCodeField.Equals(value) != true)) {
                        this.paymentAlternativeCurrencyCodeField = value;
                        this.OnPropertyChanged("PaymentAlternativeCurrencyCode");
                    }
                }
                else {
                    this.paymentAlternativeCurrencyCodeField = value;
                    this.OnPropertyChanged("PaymentAlternativeCurrencyCode");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public AccountingCostCodeType AccountingCostCode {
            get {
                return this.accountingCostCodeField;
            }
            set {
                if ((this.accountingCostCodeField != null)) {
                    if ((accountingCostCodeField.Equals(value) != true)) {
                        this.accountingCostCodeField = value;
                        this.OnPropertyChanged("AccountingCostCode");
                    }
                }
                else {
                    this.accountingCostCodeField = value;
                    this.OnPropertyChanged("AccountingCostCode");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public AccountingCostType AccountingCost {
            get {
                return this.accountingCostField;
            }
            set {
                if ((this.accountingCostField != null)) {
                    if ((accountingCostField.Equals(value) != true)) {
                        this.accountingCostField = value;
                        this.OnPropertyChanged("AccountingCost");
                    }
                }
                else {
                    this.accountingCostField = value;
                    this.OnPropertyChanged("AccountingCost");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public LineCountNumericType LineCountNumeric {
            get {
                return this.lineCountNumericField;
            }
            set {
                if ((this.lineCountNumericField != null)) {
                    if ((lineCountNumericField.Equals(value) != true)) {
                        this.lineCountNumericField = value;
                        this.OnPropertyChanged("LineCountNumeric");
                    }
                }
                else {
                    this.lineCountNumericField = value;
                    this.OnPropertyChanged("LineCountNumeric");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
        public BuyerReferenceType BuyerReference {
            get {
                return this.buyerReferenceField;
            }
            set {
                if ((this.buyerReferenceField != null)) {
                    if ((buyerReferenceField.Equals(value) != true)) {
                        this.buyerReferenceField = value;
                        this.OnPropertyChanged("BuyerReference");
                    }
                }
                else {
                    this.buyerReferenceField = value;
                    this.OnPropertyChanged("BuyerReference");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<PeriodType> InvoicePeriod {
            get {
                return this.invoicePeriodField;
            }
            set {
                if ((this.invoicePeriodField != null)) {
                    if ((invoicePeriodField.Equals(value) != true)) {
                        this.invoicePeriodField = value;
                        this.OnPropertyChanged("InvoicePeriod");
                    }
                }
                else {
                    this.invoicePeriodField = value;
                    this.OnPropertyChanged("InvoicePeriod");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public OrderReferenceType OrderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                if ((this.orderReferenceField != null)) {
                    if ((orderReferenceField.Equals(value) != true)) {
                        this.orderReferenceField = value;
                        this.OnPropertyChanged("OrderReference");
                    }
                }
                else {
                    this.orderReferenceField = value;
                    this.OnPropertyChanged("OrderReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<BillingReferenceType> BillingReference {
            get {
                return this.billingReferenceField;
            }
            set {
                if ((this.billingReferenceField != null)) {
                    if ((billingReferenceField.Equals(value) != true)) {
                        this.billingReferenceField = value;
                        this.OnPropertyChanged("BillingReference");
                    }
                }
                else {
                    this.billingReferenceField = value;
                    this.OnPropertyChanged("BillingReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DocumentReferenceType> DespatchDocumentReference {
            get {
                return this.despatchDocumentReferenceField;
            }
            set {
                if ((this.despatchDocumentReferenceField != null)) {
                    if ((despatchDocumentReferenceField.Equals(value) != true)) {
                        this.despatchDocumentReferenceField = value;
                        this.OnPropertyChanged("DespatchDocumentReference");
                    }
                }
                else {
                    this.despatchDocumentReferenceField = value;
                    this.OnPropertyChanged("DespatchDocumentReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DocumentReferenceType> ReceiptDocumentReference {
            get {
                return this.receiptDocumentReferenceField;
            }
            set {
                if ((this.receiptDocumentReferenceField != null)) {
                    if ((receiptDocumentReferenceField.Equals(value) != true)) {
                        this.receiptDocumentReferenceField = value;
                        this.OnPropertyChanged("ReceiptDocumentReference");
                    }
                }
                else {
                    this.receiptDocumentReferenceField = value;
                    this.OnPropertyChanged("ReceiptDocumentReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DocumentReferenceType> StatementDocumentReference {
            get {
                return this.statementDocumentReferenceField;
            }
            set {
                if ((this.statementDocumentReferenceField != null)) {
                    if ((statementDocumentReferenceField.Equals(value) != true)) {
                        this.statementDocumentReferenceField = value;
                        this.OnPropertyChanged("StatementDocumentReference");
                    }
                }
                else {
                    this.statementDocumentReferenceField = value;
                    this.OnPropertyChanged("StatementDocumentReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DocumentReferenceType> OriginatorDocumentReference {
            get {
                return this.originatorDocumentReferenceField;
            }
            set {
                if ((this.originatorDocumentReferenceField != null)) {
                    if ((originatorDocumentReferenceField.Equals(value) != true)) {
                        this.originatorDocumentReferenceField = value;
                        this.OnPropertyChanged("OriginatorDocumentReference");
                    }
                }
                else {
                    this.originatorDocumentReferenceField = value;
                    this.OnPropertyChanged("OriginatorDocumentReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DocumentReferenceType> ContractDocumentReference {
            get {
                return this.contractDocumentReferenceField;
            }
            set {
                if ((this.contractDocumentReferenceField != null)) {
                    if ((contractDocumentReferenceField.Equals(value) != true)) {
                        this.contractDocumentReferenceField = value;
                        this.OnPropertyChanged("ContractDocumentReference");
                    }
                }
                else {
                    this.contractDocumentReferenceField = value;
                    this.OnPropertyChanged("ContractDocumentReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DocumentReferenceType> AdditionalDocumentReference {
            get {
                return this.additionalDocumentReferenceField;
            }
            set {
                if ((this.additionalDocumentReferenceField != null)) {
                    if ((additionalDocumentReferenceField.Equals(value) != true)) {
                        this.additionalDocumentReferenceField = value;
                        this.OnPropertyChanged("AdditionalDocumentReference");
                    }
                }
                else {
                    this.additionalDocumentReferenceField = value;
                    this.OnPropertyChanged("AdditionalDocumentReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<ProjectReferenceType> ProjectReference {
            get {
                return this.projectReferenceField;
            }
            set {
                if ((this.projectReferenceField != null)) {
                    if ((projectReferenceField.Equals(value) != true)) {
                        this.projectReferenceField = value;
                        this.OnPropertyChanged("ProjectReference");
                    }
                }
                else {
                    this.projectReferenceField = value;
                    this.OnPropertyChanged("ProjectReference");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<SignatureType> Signature {
            get {
                return this.signatureField;
            }
            set {
                if ((this.signatureField != null)) {
                    if ((signatureField.Equals(value) != true)) {
                        this.signatureField = value;
                        this.OnPropertyChanged("Signature");
                    }
                }
                else {
                    this.signatureField = value;
                    this.OnPropertyChanged("Signature");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SupplierPartyType AccountingSupplierParty {
            get {
                return this.accountingSupplierPartyField;
            }
            set {
                if ((this.accountingSupplierPartyField != null)) {
                    if ((accountingSupplierPartyField.Equals(value) != true)) {
                        this.accountingSupplierPartyField = value;
                        this.OnPropertyChanged("AccountingSupplierParty");
                    }
                }
                else {
                    this.accountingSupplierPartyField = value;
                    this.OnPropertyChanged("AccountingSupplierParty");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CustomerPartyType AccountingCustomerParty {
            get {
                return this.accountingCustomerPartyField;
            }
            set {
                if ((this.accountingCustomerPartyField != null)) {
                    if ((accountingCustomerPartyField.Equals(value) != true)) {
                        this.accountingCustomerPartyField = value;
                        this.OnPropertyChanged("AccountingCustomerParty");
                    }
                }
                else {
                    this.accountingCustomerPartyField = value;
                    this.OnPropertyChanged("AccountingCustomerParty");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType PayeeParty {
            get {
                return this.payeePartyField;
            }
            set {
                if ((this.payeePartyField != null)) {
                    if ((payeePartyField.Equals(value) != true)) {
                        this.payeePartyField = value;
                        this.OnPropertyChanged("PayeeParty");
                    }
                }
                else {
                    this.payeePartyField = value;
                    this.OnPropertyChanged("PayeeParty");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public CustomerPartyType BuyerCustomerParty {
            get {
                return this.buyerCustomerPartyField;
            }
            set {
                if ((this.buyerCustomerPartyField != null)) {
                    if ((buyerCustomerPartyField.Equals(value) != true)) {
                        this.buyerCustomerPartyField = value;
                        this.OnPropertyChanged("BuyerCustomerParty");
                    }
                }
                else {
                    this.buyerCustomerPartyField = value;
                    this.OnPropertyChanged("BuyerCustomerParty");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public SupplierPartyType SellerSupplierParty {
            get {
                return this.sellerSupplierPartyField;
            }
            set {
                if ((this.sellerSupplierPartyField != null)) {
                    if ((sellerSupplierPartyField.Equals(value) != true)) {
                        this.sellerSupplierPartyField = value;
                        this.OnPropertyChanged("SellerSupplierParty");
                    }
                }
                else {
                    this.sellerSupplierPartyField = value;
                    this.OnPropertyChanged("SellerSupplierParty");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public PartyType TaxRepresentativeParty {
            get {
                return this.taxRepresentativePartyField;
            }
            set {
                if ((this.taxRepresentativePartyField != null)) {
                    if ((taxRepresentativePartyField.Equals(value) != true)) {
                        this.taxRepresentativePartyField = value;
                        this.OnPropertyChanged("TaxRepresentativeParty");
                    }
                }
                else {
                    this.taxRepresentativePartyField = value;
                    this.OnPropertyChanged("TaxRepresentativeParty");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<DeliveryType> Delivery {
            get {
                return this.deliveryField;
            }
            set {
                if ((this.deliveryField != null)) {
                    if ((deliveryField.Equals(value) != true)) {
                        this.deliveryField = value;
                        this.OnPropertyChanged("Delivery");
                    }
                }
                else {
                    this.deliveryField = value;
                    this.OnPropertyChanged("Delivery");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public DeliveryTermsType DeliveryTerms {
            get {
                return this.deliveryTermsField;
            }
            set {
                if ((this.deliveryTermsField != null)) {
                    if ((deliveryTermsField.Equals(value) != true)) {
                        this.deliveryTermsField = value;
                        this.OnPropertyChanged("DeliveryTerms");
                    }
                }
                else {
                    this.deliveryTermsField = value;
                    this.OnPropertyChanged("DeliveryTerms");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<PaymentMeansType> PaymentMeans {
            get {
                return this.paymentMeansField;
            }
            set {
                if ((this.paymentMeansField != null)) {
                    if ((paymentMeansField.Equals(value) != true)) {
                        this.paymentMeansField = value;
                        this.OnPropertyChanged("PaymentMeans");
                    }
                }
                else {
                    this.paymentMeansField = value;
                    this.OnPropertyChanged("PaymentMeans");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<PaymentTermsType> PaymentTerms {
            get {
                return this.paymentTermsField;
            }
            set {
                if ((this.paymentTermsField != null)) {
                    if ((paymentTermsField.Equals(value) != true)) {
                        this.paymentTermsField = value;
                        this.OnPropertyChanged("PaymentTerms");
                    }
                }
                else {
                    this.paymentTermsField = value;
                    this.OnPropertyChanged("PaymentTerms");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<PaymentType> PrepaidPayment {
            get {
                return this.prepaidPaymentField;
            }
            set {
                if ((this.prepaidPaymentField != null)) {
                    if ((prepaidPaymentField.Equals(value) != true)) {
                        this.prepaidPaymentField = value;
                        this.OnPropertyChanged("PrepaidPayment");
                    }
                }
                else {
                    this.prepaidPaymentField = value;
                    this.OnPropertyChanged("PrepaidPayment");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<AllowanceChargeType> AllowanceCharge {
            get {
                return this.allowanceChargeField;
            }
            set {
                if ((this.allowanceChargeField != null)) {
                    if ((allowanceChargeField.Equals(value) != true)) {
                        this.allowanceChargeField = value;
                        this.OnPropertyChanged("AllowanceCharge");
                    }
                }
                else {
                    this.allowanceChargeField = value;
                    this.OnPropertyChanged("AllowanceCharge");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType TaxExchangeRate {
            get {
                return this.taxExchangeRateField;
            }
            set {
                if ((this.taxExchangeRateField != null)) {
                    if ((taxExchangeRateField.Equals(value) != true)) {
                        this.taxExchangeRateField = value;
                        this.OnPropertyChanged("TaxExchangeRate");
                    }
                }
                else {
                    this.taxExchangeRateField = value;
                    this.OnPropertyChanged("TaxExchangeRate");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType PricingExchangeRate {
            get {
                return this.pricingExchangeRateField;
            }
            set {
                if ((this.pricingExchangeRateField != null)) {
                    if ((pricingExchangeRateField.Equals(value) != true)) {
                        this.pricingExchangeRateField = value;
                        this.OnPropertyChanged("PricingExchangeRate");
                    }
                }
                else {
                    this.pricingExchangeRateField = value;
                    this.OnPropertyChanged("PricingExchangeRate");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType PaymentExchangeRate {
            get {
                return this.paymentExchangeRateField;
            }
            set {
                if ((this.paymentExchangeRateField != null)) {
                    if ((paymentExchangeRateField.Equals(value) != true)) {
                        this.paymentExchangeRateField = value;
                        this.OnPropertyChanged("PaymentExchangeRate");
                    }
                }
                else {
                    this.paymentExchangeRateField = value;
                    this.OnPropertyChanged("PaymentExchangeRate");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ExchangeRateType PaymentAlternativeExchangeRate {
            get {
                return this.paymentAlternativeExchangeRateField;
            }
            set {
                if ((this.paymentAlternativeExchangeRateField != null)) {
                    if ((paymentAlternativeExchangeRateField.Equals(value) != true)) {
                        this.paymentAlternativeExchangeRateField = value;
                        this.OnPropertyChanged("PaymentAlternativeExchangeRate");
                    }
                }
                else {
                    this.paymentAlternativeExchangeRateField = value;
                    this.OnPropertyChanged("PaymentAlternativeExchangeRate");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<TaxTotalType> TaxTotal {
            get {
                return this.taxTotalField;
            }
            set {
                if ((this.taxTotalField != null)) {
                    if ((taxTotalField.Equals(value) != true)) {
                        this.taxTotalField = value;
                        this.OnPropertyChanged("TaxTotal");
                    }
                }
                else {
                    this.taxTotalField = value;
                    this.OnPropertyChanged("TaxTotal");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<TaxTotalType> WithholdingTaxTotal {
            get {
                return this.withholdingTaxTotalField;
            }
            set {
                if ((this.withholdingTaxTotalField != null)) {
                    if ((withholdingTaxTotalField.Equals(value) != true)) {
                        this.withholdingTaxTotalField = value;
                        this.OnPropertyChanged("WithholdingTaxTotal");
                    }
                }
                else {
                    this.withholdingTaxTotalField = value;
                    this.OnPropertyChanged("WithholdingTaxTotal");
                }
            }
        }

         [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public MonetaryTotalType LegalMonetaryTotal {
            get {
                return this.legalMonetaryTotalField;
            }
            set {
                if ((this.legalMonetaryTotalField != null)) {
                    if ((legalMonetaryTotalField.Equals(value) != true)) {
                        this.legalMonetaryTotalField = value;
                        this.OnPropertyChanged("LegalMonetaryTotal");
                    }
                }
                else {
                    this.legalMonetaryTotalField = value;
                    this.OnPropertyChanged("LegalMonetaryTotal");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2")]
        public ObservableCollection<InvoiceLineType> InvoiceLine {
            get {
                return this.invoiceLineField;
            }
            set {
                if ((this.invoiceLineField != null)) {
                    if ((invoiceLineField.Equals(value) != true)) {
                        this.invoiceLineField = value;
                        this.OnPropertyChanged("InvoiceLine");
                    }
                }
                else {
                    this.invoiceLineField = value;
                    this.OnPropertyChanged("InvoiceLine");
                }
            }
        }
        
        private static System.Xml.Serialization.XmlSerializer Serializer {
            get {
                if ((serializer == null)) {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(InvoiceType));
                }
                return serializer;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current InvoiceType object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize() {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally {
                if ((streamReader != null)) {
                    streamReader.Dispose();
                }
                if ((memoryStream != null)) {
                    memoryStream.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes workflow markup into an InvoiceType object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output InvoiceType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out InvoiceType obj, out System.Exception exception) {
            exception = null;
            obj = default(InvoiceType);
            try {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool Deserialize(string xml, out InvoiceType obj) {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }
        
        public static InvoiceType Deserialize(string xml) {
            System.IO.StringReader stringReader = null;
            try {
                stringReader = new System.IO.StringReader(xml);
                return ((InvoiceType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally {
                if ((stringReader != null)) {
                    stringReader.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Serializes current InvoiceType object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception) {
            exception = null;
            try {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e) {
                exception = e;
                return false;
            }
        }
        
        public virtual void SaveToFile(string fileName) {
            System.IO.StreamWriter streamWriter = null;
            try {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally {
                if ((streamWriter != null)) {
                    streamWriter.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes xml markup from file into an InvoiceType object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output InvoiceType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out InvoiceType obj, out System.Exception exception) {
            exception = null;
            obj = default(InvoiceType);
            try {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool LoadFromFile(string fileName, out InvoiceType obj) {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }
        
        public static InvoiceType LoadFromFile(string fileName) {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally {
                if ((file != null)) {
                    file.Dispose();
                }
                if ((sr != null)) {
                    sr.Dispose();
                }
            }
        }
        #endregion
        
        #region Clone method
        /// <summary>
        /// Create a clone of this InvoiceType object
        /// </summary>
        public virtual InvoiceType Clone() {
            return ((InvoiceType)(this.MemberwiseClone()));
        }
        #endregion
    }
}
