// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>Oasis.Ubl.v21</NameSpace><Collection>ObservableCollection</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Oasis.Ubl.v21 {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Collections.ObjectModel;
    
    
    public partial class ContractAwardNoticeType : System.ComponentModel.INotifyPropertyChanged {
        
        private ObservableCollection<UBLExtensionType> uBLExtensionsField;
        
        private UBLVersionIDType uBLVersionIDField;
        
        private CustomizationIDType customizationIDField;
        
        private ProfileIDType profileIDField;
        
        private ProfileExecutionIDType profileExecutionIDField;
        
        private IDType idField;
        
        private CopyIndicatorType copyIndicatorField;
        
        private UUIDType uUIDField;
        
        private ContractFolderIDType contractFolderIDField;
        
        private IssueDateType issueDateField;
        
        private IssueTimeType issueTimeField;
        
        private ObservableCollection<NoteType> noteField;
        
        private ObservableCollection<RegulatoryDomainType> regulatoryDomainField;
        
        private PublishAwardIndicatorType publishAwardIndicatorField;
        
        private ObservableCollection<DocumentReferenceType> previousDocumentReferenceField;
        
        private ObservableCollection<DocumentReferenceType> minutesDocumentReferenceField;
        
        private ObservableCollection<SignatureType> signatureField;
        
        private ContractingPartyType contractingPartyField;
        
        private CustomerPartyType originatorCustomerPartyField;
        
        private PartyType receiverPartyField;
        
        private TenderingTermsType tenderingTermsField;
        
        private TenderingProcessType tenderingProcessField;
        
        private ProcurementProjectType procurementProjectField;
        
        private ObservableCollection<ProcurementProjectLotType> procurementProjectLotField;
        
        private ObservableCollection<TenderResultType> tenderResultField;
        
        private static System.Xml.Serialization.XmlSerializer serializer;
        
        public ContractAwardNoticeType() {
            this.tenderResultField = new ObservableCollection<TenderResultType>();
            this.procurementProjectLotField = new ObservableCollection<ProcurementProjectLotType>();
            this.procurementProjectField = new ProcurementProjectType();
            this.tenderingProcessField = new TenderingProcessType();
            this.tenderingTermsField = new TenderingTermsType();
            this.receiverPartyField = new PartyType();
            this.originatorCustomerPartyField = new CustomerPartyType();
            this.contractingPartyField = new ContractingPartyType();
            this.signatureField = new ObservableCollection<SignatureType>();
            this.minutesDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.previousDocumentReferenceField = new ObservableCollection<DocumentReferenceType>();
            this.publishAwardIndicatorField = new PublishAwardIndicatorType();
            this.regulatoryDomainField = new ObservableCollection<RegulatoryDomainType>();
            this.noteField = new ObservableCollection<NoteType>();
            this.issueTimeField = new IssueTimeType();
            this.issueDateField = new IssueDateType();
            this.contractFolderIDField = new ContractFolderIDType();
            this.uUIDField = new UUIDType();
            this.copyIndicatorField = new CopyIndicatorType();
            this.idField = new IDType();
            this.profileExecutionIDField = new ProfileExecutionIDType();
            this.profileIDField = new ProfileIDType();
            this.customizationIDField = new CustomizationIDType();
            this.uBLVersionIDField = new UBLVersionIDType();
            this.uBLExtensionsField = new ObservableCollection<UBLExtensionType>();
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2")]
        [System.Xml.Serialization.XmlArrayItemAttribute("UBLExtension", IsNullable=false)]
        public ObservableCollection<UBLExtensionType> UBLExtensions {
            get {
                return this.uBLExtensionsField;
            }
            set {
                if ((this.uBLExtensionsField != null)) {
                    if ((uBLExtensionsField.Equals(value) != true)) {
                        this.uBLExtensionsField = value;
                        this.OnPropertyChanged("UBLExtensions");
                    }
                }
                else {
                    this.uBLExtensionsField = value;
                    this.OnPropertyChanged("UBLExtensions");
                }
            }
        }
        
        public UBLVersionIDType UBLVersionID {
            get {
                return this.uBLVersionIDField;
            }
            set {
                if ((this.uBLVersionIDField != null)) {
                    if ((uBLVersionIDField.Equals(value) != true)) {
                        this.uBLVersionIDField = value;
                        this.OnPropertyChanged("UBLVersionID");
                    }
                }
                else {
                    this.uBLVersionIDField = value;
                    this.OnPropertyChanged("UBLVersionID");
                }
            }
        }
        
        public CustomizationIDType CustomizationID {
            get {
                return this.customizationIDField;
            }
            set {
                if ((this.customizationIDField != null)) {
                    if ((customizationIDField.Equals(value) != true)) {
                        this.customizationIDField = value;
                        this.OnPropertyChanged("CustomizationID");
                    }
                }
                else {
                    this.customizationIDField = value;
                    this.OnPropertyChanged("CustomizationID");
                }
            }
        }
        
        public ProfileIDType ProfileID {
            get {
                return this.profileIDField;
            }
            set {
                if ((this.profileIDField != null)) {
                    if ((profileIDField.Equals(value) != true)) {
                        this.profileIDField = value;
                        this.OnPropertyChanged("ProfileID");
                    }
                }
                else {
                    this.profileIDField = value;
                    this.OnPropertyChanged("ProfileID");
                }
            }
        }
        
        public ProfileExecutionIDType ProfileExecutionID {
            get {
                return this.profileExecutionIDField;
            }
            set {
                if ((this.profileExecutionIDField != null)) {
                    if ((profileExecutionIDField.Equals(value) != true)) {
                        this.profileExecutionIDField = value;
                        this.OnPropertyChanged("ProfileExecutionID");
                    }
                }
                else {
                    this.profileExecutionIDField = value;
                    this.OnPropertyChanged("ProfileExecutionID");
                }
            }
        }
        
        public IDType ID {
            get {
                return this.idField;
            }
            set {
                if ((this.idField != null)) {
                    if ((idField.Equals(value) != true)) {
                        this.idField = value;
                        this.OnPropertyChanged("ID");
                    }
                }
                else {
                    this.idField = value;
                    this.OnPropertyChanged("ID");
                }
            }
        }
        
        public CopyIndicatorType CopyIndicator {
            get {
                return this.copyIndicatorField;
            }
            set {
                if ((this.copyIndicatorField != null)) {
                    if ((copyIndicatorField.Equals(value) != true)) {
                        this.copyIndicatorField = value;
                        this.OnPropertyChanged("CopyIndicator");
                    }
                }
                else {
                    this.copyIndicatorField = value;
                    this.OnPropertyChanged("CopyIndicator");
                }
            }
        }
        
        public UUIDType UUID {
            get {
                return this.uUIDField;
            }
            set {
                if ((this.uUIDField != null)) {
                    if ((uUIDField.Equals(value) != true)) {
                        this.uUIDField = value;
                        this.OnPropertyChanged("UUID");
                    }
                }
                else {
                    this.uUIDField = value;
                    this.OnPropertyChanged("UUID");
                }
            }
        }
        
        public ContractFolderIDType ContractFolderID {
            get {
                return this.contractFolderIDField;
            }
            set {
                if ((this.contractFolderIDField != null)) {
                    if ((contractFolderIDField.Equals(value) != true)) {
                        this.contractFolderIDField = value;
                        this.OnPropertyChanged("ContractFolderID");
                    }
                }
                else {
                    this.contractFolderIDField = value;
                    this.OnPropertyChanged("ContractFolderID");
                }
            }
        }
        
        public IssueDateType IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                if ((this.issueDateField != null)) {
                    if ((issueDateField.Equals(value) != true)) {
                        this.issueDateField = value;
                        this.OnPropertyChanged("IssueDate");
                    }
                }
                else {
                    this.issueDateField = value;
                    this.OnPropertyChanged("IssueDate");
                }
            }
        }
        
        public IssueTimeType IssueTime {
            get {
                return this.issueTimeField;
            }
            set {
                if ((this.issueTimeField != null)) {
                    if ((issueTimeField.Equals(value) != true)) {
                        this.issueTimeField = value;
                        this.OnPropertyChanged("IssueTime");
                    }
                }
                else {
                    this.issueTimeField = value;
                    this.OnPropertyChanged("IssueTime");
                }
            }
        }
        
        public ObservableCollection<NoteType> Note {
            get {
                return this.noteField;
            }
            set {
                if ((this.noteField != null)) {
                    if ((noteField.Equals(value) != true)) {
                        this.noteField = value;
                        this.OnPropertyChanged("Note");
                    }
                }
                else {
                    this.noteField = value;
                    this.OnPropertyChanged("Note");
                }
            }
        }
        
        public ObservableCollection<RegulatoryDomainType> RegulatoryDomain {
            get {
                return this.regulatoryDomainField;
            }
            set {
                if ((this.regulatoryDomainField != null)) {
                    if ((regulatoryDomainField.Equals(value) != true)) {
                        this.regulatoryDomainField = value;
                        this.OnPropertyChanged("RegulatoryDomain");
                    }
                }
                else {
                    this.regulatoryDomainField = value;
                    this.OnPropertyChanged("RegulatoryDomain");
                }
            }
        }
        
        public PublishAwardIndicatorType PublishAwardIndicator {
            get {
                return this.publishAwardIndicatorField;
            }
            set {
                if ((this.publishAwardIndicatorField != null)) {
                    if ((publishAwardIndicatorField.Equals(value) != true)) {
                        this.publishAwardIndicatorField = value;
                        this.OnPropertyChanged("PublishAwardIndicator");
                    }
                }
                else {
                    this.publishAwardIndicatorField = value;
                    this.OnPropertyChanged("PublishAwardIndicator");
                }
            }
        }
        
        public ObservableCollection<DocumentReferenceType> PreviousDocumentReference {
            get {
                return this.previousDocumentReferenceField;
            }
            set {
                if ((this.previousDocumentReferenceField != null)) {
                    if ((previousDocumentReferenceField.Equals(value) != true)) {
                        this.previousDocumentReferenceField = value;
                        this.OnPropertyChanged("PreviousDocumentReference");
                    }
                }
                else {
                    this.previousDocumentReferenceField = value;
                    this.OnPropertyChanged("PreviousDocumentReference");
                }
            }
        }
        
        public ObservableCollection<DocumentReferenceType> MinutesDocumentReference {
            get {
                return this.minutesDocumentReferenceField;
            }
            set {
                if ((this.minutesDocumentReferenceField != null)) {
                    if ((minutesDocumentReferenceField.Equals(value) != true)) {
                        this.minutesDocumentReferenceField = value;
                        this.OnPropertyChanged("MinutesDocumentReference");
                    }
                }
                else {
                    this.minutesDocumentReferenceField = value;
                    this.OnPropertyChanged("MinutesDocumentReference");
                }
            }
        }
        
        public ObservableCollection<SignatureType> Signature {
            get {
                return this.signatureField;
            }
            set {
                if ((this.signatureField != null)) {
                    if ((signatureField.Equals(value) != true)) {
                        this.signatureField = value;
                        this.OnPropertyChanged("Signature");
                    }
                }
                else {
                    this.signatureField = value;
                    this.OnPropertyChanged("Signature");
                }
            }
        }
        
        public ContractingPartyType ContractingParty {
            get {
                return this.contractingPartyField;
            }
            set {
                if ((this.contractingPartyField != null)) {
                    if ((contractingPartyField.Equals(value) != true)) {
                        this.contractingPartyField = value;
                        this.OnPropertyChanged("ContractingParty");
                    }
                }
                else {
                    this.contractingPartyField = value;
                    this.OnPropertyChanged("ContractingParty");
                }
            }
        }
        
        public CustomerPartyType OriginatorCustomerParty {
            get {
                return this.originatorCustomerPartyField;
            }
            set {
                if ((this.originatorCustomerPartyField != null)) {
                    if ((originatorCustomerPartyField.Equals(value) != true)) {
                        this.originatorCustomerPartyField = value;
                        this.OnPropertyChanged("OriginatorCustomerParty");
                    }
                }
                else {
                    this.originatorCustomerPartyField = value;
                    this.OnPropertyChanged("OriginatorCustomerParty");
                }
            }
        }
        
        public PartyType ReceiverParty {
            get {
                return this.receiverPartyField;
            }
            set {
                if ((this.receiverPartyField != null)) {
                    if ((receiverPartyField.Equals(value) != true)) {
                        this.receiverPartyField = value;
                        this.OnPropertyChanged("ReceiverParty");
                    }
                }
                else {
                    this.receiverPartyField = value;
                    this.OnPropertyChanged("ReceiverParty");
                }
            }
        }
        
        public TenderingTermsType TenderingTerms {
            get {
                return this.tenderingTermsField;
            }
            set {
                if ((this.tenderingTermsField != null)) {
                    if ((tenderingTermsField.Equals(value) != true)) {
                        this.tenderingTermsField = value;
                        this.OnPropertyChanged("TenderingTerms");
                    }
                }
                else {
                    this.tenderingTermsField = value;
                    this.OnPropertyChanged("TenderingTerms");
                }
            }
        }
        
        public TenderingProcessType TenderingProcess {
            get {
                return this.tenderingProcessField;
            }
            set {
                if ((this.tenderingProcessField != null)) {
                    if ((tenderingProcessField.Equals(value) != true)) {
                        this.tenderingProcessField = value;
                        this.OnPropertyChanged("TenderingProcess");
                    }
                }
                else {
                    this.tenderingProcessField = value;
                    this.OnPropertyChanged("TenderingProcess");
                }
            }
        }
        
        public ProcurementProjectType ProcurementProject {
            get {
                return this.procurementProjectField;
            }
            set {
                if ((this.procurementProjectField != null)) {
                    if ((procurementProjectField.Equals(value) != true)) {
                        this.procurementProjectField = value;
                        this.OnPropertyChanged("ProcurementProject");
                    }
                }
                else {
                    this.procurementProjectField = value;
                    this.OnPropertyChanged("ProcurementProject");
                }
            }
        }
        
        public ObservableCollection<ProcurementProjectLotType> ProcurementProjectLot {
            get {
                return this.procurementProjectLotField;
            }
            set {
                if ((this.procurementProjectLotField != null)) {
                    if ((procurementProjectLotField.Equals(value) != true)) {
                        this.procurementProjectLotField = value;
                        this.OnPropertyChanged("ProcurementProjectLot");
                    }
                }
                else {
                    this.procurementProjectLotField = value;
                    this.OnPropertyChanged("ProcurementProjectLot");
                }
            }
        }
        
        public ObservableCollection<TenderResultType> TenderResult {
            get {
                return this.tenderResultField;
            }
            set {
                if ((this.tenderResultField != null)) {
                    if ((tenderResultField.Equals(value) != true)) {
                        this.tenderResultField = value;
                        this.OnPropertyChanged("TenderResult");
                    }
                }
                else {
                    this.tenderResultField = value;
                    this.OnPropertyChanged("TenderResult");
                }
            }
        }
        
        private static System.Xml.Serialization.XmlSerializer Serializer {
            get {
                if ((serializer == null)) {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(ContractAwardNoticeType));
                }
                return serializer;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public virtual void OnPropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null)) {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current ContractAwardNoticeType object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize() {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try {
                memoryStream = new System.IO.MemoryStream();
                Serializer.Serialize(memoryStream, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally {
                if ((streamReader != null)) {
                    streamReader.Dispose();
                }
                if ((memoryStream != null)) {
                    memoryStream.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes workflow markup into an ContractAwardNoticeType object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output ContractAwardNoticeType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out ContractAwardNoticeType obj, out System.Exception exception) {
            exception = null;
            obj = default(ContractAwardNoticeType);
            try {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool Deserialize(string xml, out ContractAwardNoticeType obj) {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }
        
        public static ContractAwardNoticeType Deserialize(string xml) {
            System.IO.StringReader stringReader = null;
            try {
                stringReader = new System.IO.StringReader(xml);
                return ((ContractAwardNoticeType)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally {
                if ((stringReader != null)) {
                    stringReader.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Serializes current ContractAwardNoticeType object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, out System.Exception exception) {
            exception = null;
            try {
                SaveToFile(fileName);
                return true;
            }
            catch (System.Exception e) {
                exception = e;
                return false;
            }
        }
        
        public virtual void SaveToFile(string fileName) {
            System.IO.StreamWriter streamWriter = null;
            try {
                string xmlString = Serialize();
                System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
                streamWriter = xmlFile.CreateText();
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally {
                if ((streamWriter != null)) {
                    streamWriter.Dispose();
                }
            }
        }
        
        /// <summary>
        /// Deserializes xml markup from file into an ContractAwardNoticeType object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output ContractAwardNoticeType object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, out ContractAwardNoticeType obj, out System.Exception exception) {
            exception = null;
            obj = default(ContractAwardNoticeType);
            try {
                obj = LoadFromFile(fileName);
                return true;
            }
            catch (System.Exception ex) {
                exception = ex;
                return false;
            }
        }
        
        public static bool LoadFromFile(string fileName, out ContractAwardNoticeType obj) {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }
        
        public static ContractAwardNoticeType LoadFromFile(string fileName) {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally {
                if ((file != null)) {
                    file.Dispose();
                }
                if ((sr != null)) {
                    sr.Dispose();
                }
            }
        }
        #endregion
        
        #region Clone method
        /// <summary>
        /// Create a clone of this ContractAwardNoticeType object
        /// </summary>
        public virtual ContractAwardNoticeType Clone() {
            return ((ContractAwardNoticeType)(this.MemberwiseClone()));
        }
        #endregion
    }
}
